simonet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('allauth.urls')),
    url(r'profile/$', login_required(RedirectView.as_view(url="/", permanent=False)), name='profile'),
    url(r'^$', login_required(views.InicioView.as_view()), name="inicio"),
    url(r'^boletines/$', login_required(views.BoletinesView.as_view()), name="boletines"),
    url(r'^calendario/$', login_required(views.CalendarioView.as_view()), name="calendario"),
    url(r'^citacion/(?P<pk>[0-9]+)/$', login_required(views.CitacionDetailView.as_view()), name="citacion"),
    url(r'^tarea_evaluacion/(?P<pk>[0-9]+)/$', login_required(views.TareaDetailView.as_view()), name="tarea"),
    url(r'^reportes/$', login_required(views.ReportesView.as_view()), name="reportes"),
]

from django.conf import settings
from django.views.static import serve 
if settings.DEBUG: 
    urlpatterns += [ 
        url(r'^media/(?P<path>.*)$', serve,  {'document_root': settings.MEDIA_ROOT,}), 
    ] 

accounts/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.db import models
from curso.models import Curso

# Create your models here.



class Representante(AbstractUser):
	cedula=models.IntegerField(null=True)
	
	class Meta:		
		verbose_name = 'Representante'
		verbose_name_plural = 'Representantes'
	def get_name_or_username(self):
		if self.first_name:
			return self.first_name+" "+self.last_name
		else:
			return self.username
	def __unicode__(self):
		return self.get_name_or_username()

class Alumno(models.Model):
	SEXO=(
		('M','Masculino'),
		('F','Femenino'),
	)
	nombre=models.CharField(max_length=20)
	apellido=models.CharField(max_length=20)
	cedula=models.IntegerField(null=True)
	correo=models.EmailField(blank=True)
	nacimiento=models.DateField()
	edad=models.IntegerField()
	curso=models.ForeignKey(Curso)
	sexo=models.CharField(choices=SEXO,max_length=1)
	representante=models.ForeignKey(Representante)

	def get_full_name(self):
		return self.nombre+" "+self.apellido

	def __unicode__(self):
		return self.get_full_name()

class Lapso(models.Model):
	"""Lapso para entrega de notas"""
	LAPSO=(
		(1,'Primero'),
		(2,'Segundo'),
		(3,'Tercero'),
	)
	CALIFICACION=(
		('A','A'),
		('B','B'),
		('C','C'),
		('D','D'),
		('E','E'),
	)	
	alumno=models.ForeignKey(Alumno)
	lapso=models.IntegerField(choices=LAPSO)
	analisis=models.TextField()
	observaciones=models.TextField(blank=True)
	conclusion=models.TextField(blank=True)
	calificacion=models.CharField(choices=CALIFICACION, max_length=1,blank=True)
	proyecto=models.CharField(max_length=40)
	def __unicode__(self):
		return self.get_lapso_display()
		
class Asistencia(models.Model):
	alumno=models.ManyToManyField(Alumno)
	dia=models.DateField()
	curso=models.ForeignKey(Curso)
	def __unicode__(self):
		return str(self.dia)+" - "+self.curso.get_curso()

calendario/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from accounts.models import Representante,Alumno

# Create your models here.
class Reportes(models.Model):
	alumno=models.ForeignKey(Alumno)
	fecha=models.DateField()
	lunes=models.BooleanField()
	martes=models.BooleanField()
	miercoles=models.BooleanField()
	jueves=models.BooleanField()
	viernes=models.BooleanField()
	informacion=models.TextField(blank=True,null=True)

	def __unicode__(self):
		return str(self.fecha)


class Reuniones(models.Model):
	motivo=models.TextField()
	fecha=models.DateTimeField()

	class Meta:
		verbose_name='Reunion'
		verbose_name_plural='Reuniones'

	def __unicode__(self):
		return str(self.fecha)

class Citaciones(models.Model):
	motivo=models.TextField()
	fecha=models.DateTimeField()
	representante=models.ForeignKey(Representante)


	class Meta:
		verbose_name='Citacion'
		verbose_name_plural='Citaciones'

	def __unicode__(self):
		return str(self.fecha)

curso/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

class Curso(models.Model):
	ANIO=(
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
		('6','6'),
	)
	SECCION=(
		('A','A'),
		('B','B'),
		('C','C'),
		('D','D'),
		('E','E'),
		('F','F'),
	)
	anio=models.CharField(choices=ANIO, max_length=1)
	seccion=models.CharField(choices=SECCION, max_length=1)

	def get_curso(self):
		return self.anio+self.seccion

	def __unicode__(self):
		return self.get_curso()


class Materia(models.Model):
	materia=models.CharField(max_length=25)
	

	def __unicode__(self):
		return self.materia

HORARIO=(
	(1,'7:00 am - 9:00 am'),
	(2,'10:00 am - 12:00 m'),
	(3,'1:00 pm - 3:00 pm'),
	(4,'4:00 pm - 6:00 pm'),
)
class MateriaCurso(models.Model):
	curso=models.ForeignKey(Curso,related_name="materia")
	materia=models.ForeignKey(Materia)
	lunes=models.BooleanField()
	martes=models.BooleanField()
	miercoles=models.BooleanField()
	jueves=models.BooleanField()
	viernes=models.BooleanField()
	horario=models.IntegerField(choices=HORARIO)

	class Meta:		
		verbose_name = 'Materia del curso'
		verbose_name_plural = 'Materias del curso'
		ordering=('horario',)

	def __unicode__(self):
		return self.curso.get_curso()+" "+self.materia.materia

class TareasYEvaluaciones(models.Model):
	TIPO=(
		('TA','Tarea'),
		('EX','Examen'),
	)
	"""tareas pendientes de los alumnos"""
	curso=models.ForeignKey(Curso,related_name="tarea")
	materia=models.ForeignKey(MateriaCurso)
	tipo=models.CharField(choices=TIPO,max_length=2)
	fecha=models.DateTimeField()
	tarea=models.TextField()

	class Meta:		
		verbose_name = 'Tarea o Evaluacion'
		verbose_name_plural = 'Tareas y Evaluaciones'
	
	def __unicode__(self):
		return self.curso.get_curso()+"-"+self.get_tipo_display()+" de "+self.materia.materia.materia


		

accounts/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import (
    UserChangeForm,
    UserCreationForm
)

from accounts.models import Representante


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Representante


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Representante

accounts/views.py
from django.shortcuts import render

# Create your views here.

calendario/views.py
from django.shortcuts import render

# Create your views here.

curso/views.py
from django.shortcuts import render

# Create your views here.

simonet/views.py
from django.views.generic import TemplateView, ListView, DetailView
from accounts.models import Alumno, Representante, Lapso
from calendario.models import Citaciones, Reuniones,Reportes
from curso.models import MateriaCurso,TareasYEvaluaciones

class InicioView(ListView):
	template_name="Inicio.html"
	model=Alumno
	def get_queryset(self):
		queryset=super(InicioView,self).get_queryset()
		return queryset.filter(representante=self.request.user)

class BoletinesView(ListView):
	template_name="Boletines2.html"
	model=Alumno
	def get_queryset(self):
		queryset=super(BoletinesView,self).get_queryset()
		return queryset.filter(representante=self.request.user)
	
class CalendarioView(ListView):
	template_name="Calendario.html"
	model=Citaciones
	def get_context_data(self,*args,**kwargs):
		context=super(CalendarioView,self).get_context_data(*args,**kwargs)
		context['alumnos']=Alumno.objects.filter(representante=self.request.user)
		return context
	def get_queryset(self):
		queryset=super(CalendarioView,self).get_queryset()
		return queryset.filter(representante=self.request.user)
	


class ReportesView(ListView):
	template_name="Reporte2.html"
	model=Alumno
	def get_queryset(self):
		queryset=super(ReportesView,self).get_queryset()
		return queryset.filter(representante=self.request.user)

	
class CitacionDetailView(DetailView):
	template_name="Citaciones.html"
	model=Citaciones

class TareaDetailView(DetailView):
	template_name="Tareas.html"
	model=TareasYEvaluaciones

templates/Boletines.html
{% extends 'base.html' %}
{% load staticfiles %}
            
            {% block titulo %}Boletines{% endblock titulo %}
            {% block content %}
            <!--BEGIN PAGE WRAPPER-->
            <div id="page-wrapper">
                <!--BEGIN TITLE & BREADCRUMB PAGE-->
                <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
                    <div class="page-header pull-left">
                        <div class="page-title">
                           Boletines</div>
                    </div>
                 
                    <div class="clearfix">
                    </div>
                </div>
                <!--END TITLE & BREADCRUMB PAGE-->
                <!--BEGIN CONTENT-->
                <div class="page-content">
                    
                            {% for alumno in object_list %}

                            <div><strong>{{alumno.get_full_name}}</strong></div>
                           
                                {% for lapso in alumno.lapso_set.all|dictsortreversed:"lapso" %}
                                <div class="row">
                                    <div class="col-md-8 panel-blue"><h4>Boletin</h2></div>
                                    <div class="col-md-4"><strong>Lapso: {{lapso.get_lapso_display}}</strong></div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12"><strong>Curso:</strong> {{alumno.curso.get_curso}}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12"><strong>Alumno:</strong> {{alumno.get_full_name}}</div>
                                </div>

                                {% if alumno.cedula %}
                                <div class="row">
                                    <div class="col-md-12"><strong>Cedula:</strong> {{alumno.cedula}}</div>
                                </div>
                                {% endif %}
                                <div class="row">
                                    <div class="col-md-4"><strong>Fecha de nacimiento:</strong> {{alumno.nacimiento|date:"d-m-y"}}</div>
                                    <div class="col-md-4"><strong>Edad:</strong> {{alumno.edad}}</div>
                                    <div class="col-md-4"><strong>sexo:</strong>{{alumno.sexo}}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12"><strong>Proyecto del Lapso:</strong> {{lapso.proyecto}}</div>
                                   
                                </div>
                                <div class="row">
                                    <div class="col-md-12" style="text-align:center"><strong>Resultados del Aprendizaje</strong></div>
                                   
                                </div>
                                <div class="row">
                                    <div class="col-md-12">{{lapso.analisis}}</div>
                                   
                                </div>
                                {% if lapso.calificacion %}
                                <div class="row">
                                    <div class="col-md-12"><strong>Calificación</strong> {{lapso.calificacion}}</div>
                                   
                                </div>
                                {% endif %}
                                {% if lapso.conclusion %}
                                <div class="row">
                                    <div class="col-md-12" style="text-align:center"><strong>Conclusión</strong></div>
                                   
                                </div>
                                <div class="row">
                                    <div class="col-md-12">{{lapso.conclusion}}</div>
                                   
                                </div>
                                {% endif %}
                                    {% endfor %}
                            {% endfor %}
                              
                   </div>
                   
                </div>
                <!--END CONTENT-->
                {% endblock content  %}
                

templates/Boletines2.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titulo %}Boletines{% endblock titulo %}
{% block content %}
<!--BEGIN PAGE WRAPPER-->
<div id="page-wrapper">
    <!--BEGIN TITLE & BREADCRUMB PAGE-->
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">
                Boletines</div>
            </div>

            <div class="clearfix">
            </div>
        </div>

        <!--END TITLE & BREADCRUMB PAGE-->
        <!--BEGIN CONTENT-->
        <div class="page-content">

            {% if object_list %}

            <div class="col-lg-12">
                <div class="panel panel-blue" style="background:#FFF;">
                    <div class="panel-heading">Boletines</div>
                    <div class="panel-body table-responsive">
                        <table id="boletin" class="table table-hover table-bordered table-condensed">
                            <thead>
                                <select  id="selectAlum" style="width:100px">
                                    {% for alumno in object_list %}
                                    <option value="{{alumno.id}}alumno">{{alumno.nombre}}</option>

                                    {% endfor %}
                                </select>
                                <p style=" margin-botton: 50px"></p>
                                <tr>

                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>Edad</th>
                                    <th>Sexo</th>
                                    <th>Curso</th>
                                    <th>Lapso</th>
                                    <th>Proyecto de Lapso</th>
                                    <th>Calificación</th>
                                    <th>Resultados del Apredizaje</th>
                                    <th>Conclusion</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for alumno in object_list %}
                                <div >

                                    {% for lapso in alumno.lapso_set.all|dictsortreversed:"lapso" %}

                                    <tr class="lapsos {{alumno.id}}alumno">
                                        <div id="{{lapso.id}}info" class="modal fade">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">
                                                            &times;</button>
                                                            <h4 class="modal-title">
                                                                Análisis</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>
                                                                    {{lapso.analisis}}</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" data-dismiss="modal" class="btn btn-default">
                                                                        Close</button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div id="{{lapso.id}}conclu" class="modal fade">
                                                            <div class="modal-dialog">
                                                                <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">
                                                                            &times;</button>
                                                                            <h4 class="modal-title">
                                                                                Resultados de Aprendizaje</h4>
                                                                            </div>
                                                                            <div class="modal-body">
                                                                                <p>
                                                                                    {{lapso.conclusion}}</p>
                                                                                </div>
                                                                                <div class="modal-footer">
                                                                                    <button type="button" data-dismiss="modal" class="btn btn-default">
                                                                                        Close</button>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>

                                                                        <td>{{alumno.nombre}}</td>
                                                                        <td>{{alumno.apellido}}</td>
                                                                        <td>{{alumno.edad}}</td>
                                                                        <td>  {{alumno.sexo}} </td>
                                                                        <td>{{alumno.curso.get_curso}}</td>
                                                                        <td>{{lapso.get_lapso_display}}</td>
                                                                        <td>{{lapso.proyecto}}</td>
                                                                        <td>{% if lapso.calificacion %}{{lapso.calificacion}}{% endif %}</td>

                                                                        <td style="text-align:center">

                                                                            <div class="tools">
                                                                                <button data-toggle="modal" data-target="#{{lapso.id}}info">Análisis
                                                                                    <i class="fa fa-chevron-down"></i>
                                                                                </button>
                                                                            </div>
                                                                        </td>
                                                                        <td style="text-align:center">  
                                                                            {% if lapso.conclusion %}
                                                                            <button data-toggle="modal" data-target="#{{lapso.id}}conclu">Conclusión
                                                                                <i class="fa fa-chevron-down"></i>
                                                                            </button>
                                                                            {% endif %}
                                                                        </td>
                                                                    </tr>


                                                                    {% endfor %}
                                                                </div>
                                                                {% endfor %}

                                                            </tbody>

                                                        </table>



                                                        {% else %}
                                                        <div class="alert alert-warning alert-dismissable">
                                                            <button type="button" data-dismiss="alert" aria-hidden="true" class="close">&times;</button>
                                                            <strong>Atencion!</strong> La Carga de Boletines aun no se ha realizado.
                                                        </div>
                                                        {% endif %}

                                                    </div>
                                                </div>

                                            </div>
                                            <!--END CONTENT-->
                                            {% endblock content  %}

                                            {% block js %}
                                            <script type="text/javascript">

                                                $('#selectAlum').on('change',function(){
                                                    
                                                    $(".lapsos").hide();
                                                    $("."+$("#selectAlum").val()).show().each(function(index){
                                                        $(this).show();
                                                    }); 
                                                    
                                                });
                                            </script>
                                            {% endblock js %}

templates/Citaciones.html
{% extends 'base.html' %}
{% load staticfiles %}

    {% block css %}
    
    <link href="styles/pnotify.custom.min.css" media="all" rel="stylesheet" type="text/css" />
        {% endblock css %}

            {% block titulo %}Citaciones{% endblock titulo %}
            {% block content %}
   <!--BEGIN PAGE WRAPPER-->
            <div id="page-wrapper">
                <!--BEGIN TITLE & BREADCRUMB PAGE-->
                <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
                    <div class="page-header pull-left">
                        <div class="page-title">
                            Horarios</div>
                    </div>
                 
                    <div class="clearfix">
                    </div>
                </div>
                <!--END TITLE & BREADCRUMB PAGE-->
                <!--BEGIN CONTENT-->
                <div class="page-content">
                   <div class="col-lg-12">
                        <div class="panel panel-blue" style="background:#FFF;">
                            <div class="panel-heading">Citación</div>
                        <div>
                            <div id="descripcion"><p style="font-size:18px;">{{object.motivo}}</p></div>
                            <div id="fecha"><p style="font-size:16px;">{{object.fecha|date:"h:m d/m/y"}}</p></div>
                        </div>
                    </div>
                   
                </div>
                <!--END CONTENT-->
                <!--BEGIN FOOTER-->
                <div id="footer">
                    <div class="copyright">
                        <a href="http://Simonet.com.ve">2016 © Simonet. Todos los derechos reservados</a></div>
                </div>
                <!--END FOOTER-->
            </div>
                <!--END CONTENT-->
                {% endblock content %}

                    
                            

templates/Inicio.html
{% extends 'base.html' %}
{% load staticfiles %}

    {% block css %}
    
    <link href="styles/pnotify.custom.min.css" media="all" rel="stylesheet" type="text/css" />
        {% endblock css %}

            {% block titulo %}Citaciones{% endblock titulo %}
            {% block content %}
   <!--BEGIN PAGE WRAPPER-->
            <div id="page-wrapper">
                <!--BEGIN TITLE & BREADCRUMB PAGE-->
                <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
                    <div class="page-header pull-left">
                        <div class="page-title">
                            Horarios</div>
                    </div>
                 
                    <div class="clearfix">
                    </div>
                </div>
                <!--END TITLE & BREADCRUMB PAGE-->
                <!--BEGIN CONTENT-->
                <div class="page-content">
                    {% for alumno in object_list %}
                   <div class="col-lg-12">
                        <div class="panel panel-blue" style="background:#FFF;">
                            <div class="panel-heading">{{alumno.get_full_name}}</div>
                            <div class="panel-body table-responsive">
                                <table class="table table-hover table-bordered table-condensed">
                                    <thead>
                                                            
                                    <p style=" margin-botton: 50px"></p>
                                    <tr>
                                       
                                        <th>Horario</th>
                                        <th>Lunes</th>
                                        <th>Martes</th>
                                        <th>Miercoles</th>
                                        <th>Jueves</th>
                                        <th>Viernes</th>
                                        
                                        
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for materia in alumno.curso.materia.all %}
                                    <tr>
                                            {% if materia.horario %}
                                                <td>{{materia.get_horario_display}}</td>

                                            {% else %}
                                                <td></td>
                                            {% endif %}

                                            {% if materia.lunes %}
                                                <td>{{materia.materia}}</td>

                                            {% else %}
                                                <td></td>
                                            {% endif %}

                                            {% if materia.martes %}
                                                <td>{{materia.materia}}</td>

                                            {% else %}
                                                <td></td>
                                            {% endif %}

                                            {% if materia.miercoles %}
                                                <td>{{materia.materia}}</td>

                                            {% else %}
                                                <td></td>
                                            {% endif %}

                                            {% if materia.jueves %}
                                                <td>{{materia.materia}}</td>

                                            {% else %}
                                                <td></td>
                                            {% endif %}

                                            {% if materia.viernes %}
                                                <td>{{materia.materia}}</td>

                                            {% else %}
                                                <td></td>
                                            {% endif %}
                                    </tr>
                                    {% endfor %}
                                    
                                    </tbody>

                                </table>
                            </div>

                    </div>
                   
                </div>
                {% endfor %}
                <!--END CONTENT-->
                <!--BEGIN FOOTER-->
                <div id="footer">
                    <div class="copyright">
                        <a href="http://Simonet.com.ve">2016 © Simonet. Todos los derechos reservados</a></div>
                </div>
                <!--END FOOTER-->
            </div>
                <!--END CONTENT-->
                {% endblock content %}

templates/Reporte.html
{% extends 'base.html' %}
{% load staticfiles %}

            {% block titulo %}Reportes{% endblock titulo %}
            {% block content %}
            <!--BEGIN PAGE WRAPPER-->
            <div id="page-wrapper">
                <!--BEGIN TITLE & BREADCRUMB PAGE-->
                <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
                    <div class="page-header pull-left">
                        <div class="page-title">
                           Reportes</div>
                    </div>
                 
                    <div class="clearfix">
                    </div>
                </div>
                <!--END TITLE & BREADCRUMB PAGE-->
                <!--BEGIN CONTENT-->
                <div class="page-content">
                    
                   {% for object in object_list %}
                            <div>
                                <div id="descripcion">{{object.motivo}}</div>
                                <div id="fecha">{{object.fecha|date:"h:m d/m/y"}}</div>
                            </div>
                            
                        {% endfor %}
                </div>
                <!--END CONTENT-->
                {% endblock content %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>
<form method="post" action=".">
{% csrf_token %}
{{form.as_p}}

<input type="submit" name="Login">
</form>
</body>
</html>